name: Build and Deploy

on:
  workflow_dispatch:
  push:
    branches: 
      - main
      - dev2-afternoon

env:
  AZURE_WEBAPP_NAME_API: ${{ vars.AZURE_WEBAPP_NAME_API }}
  AZURE_WEBAPP_NAME_WEB: ${{ vars.AZURE_WEBAPP_NAME_WEB }}
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
      # Add this step
    - name: Set up .env
      run: echo "REACT_APP_API_BASE_URL=https://${{ vars.AZURE_WEBAPP_NAME_API }}.azurewebsites.net/api" > ./src/web/.env.production

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ env.AZURE_CREDENTIALS }}

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'

    - name: Build and publish API
      run: |
        cd src/api
        dotnet publish --configuration Release --output ./output
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: '1'

    - name: Deploy API to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME_API }}
        package: ./src/api/output

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'

    - name: Build and publish Web
      run: |
        cd src/web
        npm ci
        npm run build
      env:
        CI: true

    - name: Deploy Web to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME_WEB }}
        package: ./src/web/build
